#!/bin/bash

echo "=========================================="
echo "x402 Mainnet Payment Instructions"
echo "=========================================="
echo ""
echo "NEW FACILITATOR WALLET:"
echo "Address: H7T5exF4PKCgR1qKxa7nJDJMreDGyn88SGfmoPP18FS1"
echo ""
echo "STEP 1: Fund Facilitator with SOL (for gas fees)"
echo "----------------------------------------------"
echo "Send 0.01 SOL to: H7T5exF4PKCgR1qKxa7nJDJMreDGyn88SGfmoPP18FS1"
echo ""
echo "Using Phantom:"
echo "  1. Open Phantom wallet"
echo "  2. Click Send"
echo "  3. Paste: H7T5exF4PKCgR1qKxa7nJDJMreDGyn88SGfmoPP18FS1"
echo "  4. Send 0.01 SOL"
echo ""
echo "Using CLI:"
echo "  solana transfer H7T5exF4PKCgR1qKxa7nJDJMreDGyn88SGfmoPP18FS1 0.01"
echo ""
echo "STEP 2: Payment Requirements"
echo "----------------------------------------------"
echo "Amount: 0.01 USDC (10,000 atomic units)"
echo "From: Your wallet with USDC"
echo "To: H7T5exF4PKCgR1qKxa7nJDJMreDGyn88SGfmoPP18FS1"
echo ""
echo "STEP 3: Test Payment Endpoint"
echo "----------------------------------------------"
echo "curl http://localhost:8402/v1/x402/demo/protected"
echo ""
echo "=========================================="
echo ""
echo "Check Solscan:"
echo "https://solscan.io/account/H7T5exF4PKCgR1qKxa7nJDJMreDGyn88SGfmoPP18FS1"
echo ""
